# Generated by Django 5.2.3 on 2025-07-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='function',
            field=models.ManyToManyField(blank=True, null=True, to='article.function'),
        ),
        migrations.AlterField(
            model_name='article',
            name='shortcut',
            field=models.ManyToManyField(blank=True, null=True, to='article.shortcut'),
        ),
    ]
